file_dict={
"/vols/cms04/kjd110/mc8/cmssm_mc8_all.root"        : {'title':"CMSSM post-LHC",'label': 'post-LHC' } , 
"/vols/cms04/kjd110/mc8/cmssm_mc8_Nov12_bsmm.root" : {'label': "Jul '12 + bsmm  "} ,
"/vols/cms04/kjd110/mc8/cmssm_mc8_HCP12_bsmm.root" : {'label': "HCP '12"},
"/vols/cms04/kjd110/mc8/nuhm1_mc8_all.root"        : {'title':"NUHM1 post-LHC",'label': "post-LHC"}  , 
"/vols/cms04/kjd110/mc8/nuhm1_mc8_Nov12_bsmm.root" : {'label': "Jul '12 + bsmm"} ,
"/vols/cms04/kjd110/mc8/nuhm1_mc8_HCP12_bsmm.root" : {'label': "HCP '12"},
"/vols/cms04/kjd110/mn_parallel//nuhm2_all_boxes_combined.root":{'title':"NUHM2 multinest 9.0M points"},
"/vols/cms04/kjd110/mc8/cmssm_mc8_all_tanb_cut.root" :{'title': r'CMSSM $\tan(\beta)<43$' },
'/vols/cms04/kjd110/mc8/nuhm1_mc8_region_c_stau_nlsp.root' : {'title': r'NUHM1, coannihilation region, $\tilde{\tau}_1$ is NLSP'},
'/vols/cms04/kjd110/mc8/nuhm1_mc8_region_c_neu2_nlsp.root' : {'title': r'NUHM1, coannihilation region, $\tilde{\chi}^0_{2}$ is NLSP'},
'/vols/cms04/kjd110/nuhm2_xmas/nuhm2_all_xmas_combined.root':{'title':"NUHM2 multinest 9.0M points with $\chi^2<45$ (of 38M) "},
'/vols/cms04/kjd110/mc8/cmssm_pre_lhc.root' : {'title':"CMSSM pre-LHC",'label': 'pre-LHC ' },
'/vols/cms04/kjd110/mc8/nuhm1_pre_lhc.root' : {'title':"NUHM1 pre-LHC",'label': 'pre-LHC ' },
                }
